In [77]:
# A smaller subsection of 156 responses were generated for manual and API calls (total 312).
# These sentences were more ambiguous and designed to suggest more than one
# The responses below are API calls
import pandas as pd
aapi = pd.read_csv("responses/ambiguous_responses_raw.csv")
aapi.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-20T06:08:05+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","In this sentence, the word ""bank"" refers to the land alongside a river or stream.",bank_river,True
1,run_2,2026-03-20T06:08:10+00:00,gpt-4.1-mini,0,300,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","Step 1: Identify the context of the sentence. \nThe sentence is: ""They sat on the bank after wi...",bank_river,True
2,run_3,2026-03-20T06:08:12+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",Answer: a financial institution,bank_fin,False
3,run_4,2026-03-20T06:08:18+00:00,gpt-4.1-mini,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Let's analyze the sentence step by step:\n\n1. The sentence is: ""They sat on the bank after with...",bank_river,True
4,run_5,2026-03-20T06:08:23+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...","In this sentence, the word ""bank"" refers to the land alongside a river or lake. The mention of ""...",bank_river,True

In [78]:
aapi.isna().sum()

response_id           0
timestamp_utc         0
model                 0
temperature           0
max_output_tokens     0
prompt_id             0
run_id                0
target_word           0
sense_id              0
gold_sense            0
sense_family          0
context_type          0
few_shot_policy_id    0
query_mode            0
sentence              0
prompt_text           0
response_text         0
predicted_sense       7
correct               0
dtype: int64

In [79]:
# 7 responses in API call were cut due to length constraint of 300 tokens. 
# These responses will be dropped, with tokens increased to 500 to gather
# full responses.
aapi_drop = aapi.dropna()
aapi_drop.isna().sum()

response_id           0
timestamp_utc         0
model                 0
temperature           0
max_output_tokens     0
prompt_id             0
run_id                0
target_word           0
sense_id              0
gold_sense            0
sense_family          0
context_type          0
few_shot_policy_id    0
query_mode            0
sentence              0
prompt_text           0
response_text         0
predicted_sense       0
correct               0
dtype: int64

In [80]:
laapi = pd.read_csv("responses/long_ambiguous_responses_raw.csv")
laapi.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_2,2026-03-22T04:20:13+00:00,gpt-4.1-mini,0,500,cot_zero_v1,1,pitch,pitch_sales,sales_communication,communication,business_communication,same_word_cross_sense,api,"He adjusted his pitch slightly, hoping the crowd would respond better.","Sentence: ""He adjusted his pitch slightly, hoping the crowd would respond better.""\n\nQuestion:\...","Step-by-step reasoning:\n\n1. Identify the context: The sentence mentions ""He adjusted his pitch...",pitch_tone,False
1,run_2,2026-03-22T04:37:29+00:00,deepseek-chat,0,500,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","Let’s break this down step by step. \n\n1. **First, look at the sentence structure and key acti...",bank_river,True
2,run_6,2026-03-22T04:37:53+00:00,deepseek-chat,0,500,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...",Let’s break this down step by step. \n\n1. **Read the sentence**: \n *“The bank was quiet th...,bank_river,True
3,run_10,2026-03-22T04:38:20+00:00,deepseek-chat,0,500,cot_zero_v1,1,pitch,pitch_sales,sales_communication,communication,business_communication,same_word_cross_sense,api,"He adjusted his pitch slightly, hoping the crowd would respond better.","Sentence: ""He adjusted his pitch slightly, hoping the crowd would respond better.""\n\nQuestion:\...",Let’s break this down step by step. \n\n1. **Context clues in the sentence** \n - The subjec...,pitch_sales,True
4,run_12,2026-03-22T04:38:34+00:00,deepseek-chat,0,500,cot_few_v1,1,pitch,pitch_sales,sales_communication,communication,business_communication,same_word_cross_sense,api,"He adjusted his pitch slightly, hoping the crowd would respond better.","Sentence: ""She stepped forward to pitch the stone into the lake.""\nQuestion:\nIn this sentence, ...",Let’s break this down step by step. \n\n1. **Look at the context clues in the sentence:** \n ...,pitch_sales,True

In [81]:
# 156 manual responses from
aman = pd.read_excel("responses/manual_ambiguous_responses_raw.xlsm")
aman.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-22 01:13:22,gpt-5.2,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","In this sentence, **“bank”** means **the land along the side of a river** (a riverbank).\n\nEven...",bank_river,True
1,run_2,2026-03-22 01:13:26,gpt-5.2,ui_default,ui_default,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...",“Bank” here means **the side of a river or stream**.\n\nReasoning summary: the sentence includes...,bank_river,True
2,run_3,2026-03-22 01:14:15,gpt-5.2,ui_default,ui_default,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",the land alongside a river,bank_river,True
3,run_4,2026-03-22 01:14:22,gpt-5.2,ui_default,ui_default,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",The sentence is ambiguous because it includes clues for both meanings of **bank**:\n\n* **“withd...,bank_river,True
4,run_5,2026-03-22 01:14:33,gpt-5.2,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...","It means the **side of a river or pond**.\n\nThe clue is **“ducks nearby,”** which suggests a na...",bank_river,True

In [82]:
pd.set_option('display.max_colwidth', 100)
aapi_man = pd.concat([aapi_drop,aman,laapi],ignore_index=True)
aapi_man.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-20T06:08:05+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","In this sentence, the word ""bank"" refers to the land alongside a river or stream.",bank_river,True
1,run_2,2026-03-20T06:08:10+00:00,gpt-4.1-mini,0,300,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","Step 1: Identify the context of the sentence. \nThe sentence is: ""They sat on the bank after wi...",bank_river,True
2,run_3,2026-03-20T06:08:12+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",Answer: a financial institution,bank_fin,False
3,run_4,2026-03-20T06:08:18+00:00,gpt-4.1-mini,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Let's analyze the sentence step by step:\n\n1. The sentence is: ""They sat on the bank after with...",bank_river,True
4,run_5,2026-03-20T06:08:23+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...","In this sentence, the word ""bank"" refers to the land alongside a river or lake. The mention of ""...",bank_river,True

In [83]:
aapi_man['query_mode'].value_counts()

query_mode
api       156
manual    156
Name: count, dtype: int64

In [84]:
aapi_man.shape

(312, 19)

In [85]:
aapi_man['model'].value_counts()

model
deepseek-chat               104
gpt-4.1-mini                 52
claude-sonnet-4-20250514     52
gpt-5.2                      52
claude-sonnet-4-5            52
Name: count, dtype: int64

In [86]:
aapi_man['correct'].value_counts()

correct
True     280
False     32
Name: count, dtype: int64

In [87]:
#Creating a subset of only the columns needed
sub = (
    aapi_man[['sentence','query_mode','correct']]
    .copy()
    .assign(
        prompt_style=aapi_man['prompt_id'].str.split('_').str[0],
        shot=aapi_man['prompt_id'].str.split('_').str[1],
        model=aapi_man['model'].str.split('-').str[0]
    )
)
new_order = ['sentence','model','query_mode','prompt_style','shot','correct']
sub = sub[new_order]
sub.head()

,sentence,model,query_mode,prompt_style,shot,correct
0,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,zero,True
1,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,zero,True
2,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,few,False
3,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,few,True
4,"The bank was quiet that morning, aside from the sound of ducks nearby.",gpt,api,direct,zero,True

In [88]:
sub['condition'] = sub['query_mode'].astype(str)+"_"+sub['prompt_style'].astype(str)+"_"+sub['shot'].astype(str)
sub.head()

,sentence,model,query_mode,prompt_style,shot,correct,condition
0,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,zero,True,api_direct_zero
1,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,zero,True,api_cot_zero
2,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,few,False,api_direct_few
3,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,few,True,api_cot_few
4,"The bank was quiet that morning, aside from the sound of ducks nearby.",gpt,api,direct,zero,True,api_direct_zero

In [89]:
sub['condition'].value_counts()

condition
api_direct_zero       39
api_cot_zero          39
api_direct_few        39
api_cot_few           39
manual_direct_zero    39
manual_cot_zero       39
manual_direct_few     39
manual_cot_few        39
Name: count, dtype: int64

In [90]:
dupes = (
    sub.groupby(['sentence', 'model', 'condition'])
       .size()
       .reset_index(name='n')
       .query('n > 1')
)

dupes.head()

,sentence,model,condition,n
72,He placed the file on the table next to the metal tools.,claude,api_cot_few,2
73,He placed the file on the table next to the metal tools.,claude,api_cot_zero,2
74,He placed the file on the table next to the metal tools.,claude,api_direct_few,2
75,He placed the file on the table next to the metal tools.,claude,api_direct_zero,2
76,He placed the file on the table next to the metal tools.,claude,manual_cot_few,2

In [91]:
check = (
    sub.groupby(['sentence', 'model', 'condition'])['correct']
       .nunique()
       .reset_index(name='n_unique')
)

check.query('n_unique > 1').head(20)

Empty DataFrame
Columns: [sentence, model, condition, n_unique]
Index: []

In [92]:
sub_dedup = sub.drop_duplicates()

In [93]:
sub_dedup.shape

(288, 7)

In [94]:
sub_dedup['correct'].value_counts()

correct
True     257
False     31
Name: count, dtype: int64

In [95]:
sub_dedup.to_csv("ambiguous_dedup.csv",index=False)

PermissionError: [Errno 13] Permission denied: 'ambiguous_dedup.csv'

In [96]:
sub_wide = pd.pivot_table(
    sub_dedup,
    values='correct',
    index=['sentence','model'],
    columns='condition',
    aggfunc='first'
)
sub_wide.head()

condition                                                                        api_cot_few  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude           True
                                                                       deepseek         True
                                                                       gpt              True
He adjusted his pitch slightly, hoping the crowd would respond better. claude           True
                                                                       deepseek         True

condition                                                                        api_cot_zero  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude            True
                                                                       deepseek          True
                                                                       gpt               True
He adjusted his pitch slightly, hoping the crowd would respond better. claude           False
                                                                       deepseek          True

condition                                                                        api_direct_few  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude              True
                                                                       deepseek            True
                                                                       gpt                 True
He adjusted his pitch slightly, hoping the crowd would respond better. claude              True
                                                                       deepseek            True

condition                                                                        api_direct_zero  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude               True
                                                                       deepseek             True
                                                                       gpt                  True
He adjusted his pitch slightly, hoping the crowd would respond better. claude              False
                                                                       deepseek             True

condition                                                                        manual_cot_few  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude              True
                                                                       deepseek            True
                                                                       gpt                 True
He adjusted his pitch slightly, hoping the crowd would respond better. claude              True
                                                                       deepseek           False

condition                                                                        manual_cot_zero  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude               True
                                                                       deepseek            False
                                                                       gpt                  True
He adjusted his pitch slightly, hoping the crowd would respond better. claude              False
                                                                       deepseek            False

condition                                                                        manual_direct_few  \
sentence                                                               model
A small ring was the only thing found near the old bell.               claude                 True
                                                                       deepseek              False
                                                                       gpt                    True
He adjusted his pitch slightly, hoping the crowd would respond better. claude                 True
                                                                       deepseek              False

condition                                                                        manual_direct_zero
sentence                                                               model
A small ring was the only thing found near the old bell.               claude                  True
                                                                       deepseek                True
                                                                       gpt                     True
He adjusted his pitch slightly, hoping the crowd would respond better. claude                 False
                                                                       deepseek               False

Comparisons:    
CoT vs Direct  
Few vs Zero  
Manual vs API  
CoT Few vs CoT Zero  
Direct Few vs Direct Zero

In [97]:
for col in sub_wide.columns:
    if col not in ['sentence', 'model']:
        sub_wide[col] = sub_wide[col].astype(bool)

In [98]:
sub_wide_df = sub_wide.reset_index()
sub_wide_df.head()

condition,sentence,model,api_cot_few,api_cot_zero,api_direct_few,api_direct_zero,manual_cot_few,manual_cot_zero,manual_direct_few,manual_direct_zero
0,A small ring was the only thing found near the old bell.,claude,True,True,True,True,True,True,True,True
1,A small ring was the only thing found near the old bell.,deepseek,True,True,True,True,True,False,False,True
2,A small ring was the only thing found near the old bell.,gpt,True,True,True,True,True,True,True,True
3,"He adjusted his pitch slightly, hoping the crowd would respond better.",claude,True,False,True,False,True,False,True,False
4,"He adjusted his pitch slightly, hoping the crowd would respond better.",deepseek,True,True,True,True,False,False,False,False

In [ ]:
sub_wide_df.to_csv("ambiguous_sub_sentence.csv", index=False)

In [103]:
#Function to run McNemar Tests
from statsmodels.stats.contingency_tables import mcnemar

def run_mcnemar(df, colA, colB):

    tmp = df[[colA, colB]].dropna().copy()

    table = pd.crosstab(tmp[colA], tmp[colB])
    table = table.reindex(index=[False, True], columns=[False, True], fill_value=0)

    b = table.loc[True, False]
    c = table.loc[False, True]
    n = b + c
#adding different tests per number discordant pairs
    if n <= 25:
        result = mcnemar(table, exact=True)
        test_type = "exact"
    else:
        result = mcnemar(table, exact=False, correction=True)
        test_type = "asymptotic"

    return table, result.pvalue, n, test_type

In [100]:
# Comparison conditions
comparison_specs = {
    "CoT vs Direct": [
        ("api_cot_zero", "api_direct_zero"),
        ("api_cot_few", "api_direct_few"),
        ("manual_cot_zero", "manual_direct_zero"),
        ("manual_cot_few", "manual_direct_few"),
    ],
    "Few vs Zero": [
        ("api_cot_few", "api_cot_zero"),
        ("api_direct_few", "api_direct_zero"),
        ("manual_cot_few", "manual_cot_zero"),
        ("manual_direct_few", "manual_direct_zero"),
    ],
    "Manual vs API": [
        ("manual_cot_zero", "api_cot_zero"),
        ("manual_cot_few", "api_cot_few"),
        ("manual_direct_zero", "api_direct_zero"),
        ("manual_direct_few", "api_direct_few"),
    ],
    "CoT Few vs CoT Zero": [
        ("api_cot_few", "api_cot_zero"),
        ("manual_cot_few", "manual_cot_zero"),
    ],
    "Direct Few vs Direct Zero": [
        ("api_direct_few", "api_direct_zero"),
        ("manual_direct_few", "manual_direct_zero"),
    ],
}

results = []

In [101]:
print(sub_wide_df['manual_cot_zero'].value_counts(), sub_wide_df['manual_direct_zero'].value_counts())

manual_cot_zero
True     30
False     6
Name: count, dtype: int64 manual_direct_zero
True     31
False     5
Name: count, dtype: int64

In [105]:
for model_name in sub_wide_df["model"].dropna().unique():
    df_model = sub_wide_df[sub_wide_df["model"] == model_name].copy()

    for comparison_name, pairs in comparison_specs.items():
        for colA, colB in pairs:
            table, pvalue, n, test_type = run_mcnemar(df_model, colA, colB)

            # Safely extract 2x2 counts even if some combinations are absent
            a = table.loc[True, True] if True in table.index and True in table.columns else 0
            b = table.loc[True, False] if True in table.index and False in table.columns else 0
            c = table.loc[False, True] if False in table.index and True in table.columns else 0
            d = table.loc[False, False] if False in table.index and False in table.columns else 0

            results.append({
                "model": model_name,
                "comparison": comparison_name,
                "condition_A": colA,
                "condition_B": colB,
                "both_correct": a,
                "A_correct_B_wrong": b,
                "A_wrong_B_correct": c,
                "both_wrong": d,
                "p_value": pvalue
            })

results_df = pd.DataFrame(results)
results_df.head()

,model,comparison,condition_A,condition_B,both_correct,A_correct_B_wrong,A_wrong_B_correct,both_wrong,p_value
0,claude,CoT vs Direct,api_cot_zero,api_direct_zero,9,1,0,2,1.0
1,claude,CoT vs Direct,api_cot_few,api_direct_few,11,0,0,1,1.0
2,claude,CoT vs Direct,manual_cot_zero,manual_direct_zero,10,0,0,2,1.0
3,claude,CoT vs Direct,manual_cot_few,manual_direct_few,11,0,1,0,1.0
4,claude,Few vs Zero,api_cot_few,api_cot_zero,10,1,0,1,1.0

In [106]:
results_df.to_csv("ambiguous_mcnemar_results.csv",index=False)

PermissionError: [Errno 13] Permission denied: 'ambiguous_mcnemar_results.csv'

In [107]:
sub_dedup.head()

,sentence,model,query_mode,prompt_style,shot,correct,condition
0,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,zero,True,api_direct_zero
1,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,zero,True,api_cot_zero
2,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,few,False,api_direct_few
3,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,few,True,api_cot_few
4,"The bank was quiet that morning, aside from the sound of ducks nearby.",gpt,api,direct,zero,True,api_direct_zero

In [108]:
#Primary tests
#API vs Manual
api_manual_wide = pd.pivot_table(
    sub_dedup,
    values='correct',
    index=['sentence', 'model', 'prompt_style', 'shot'],
    columns='query_mode',
    aggfunc='first'
).reset_index()

print(api_manual_wide.shape)
print(api_manual_wide.head())

(144, 6)
query_mode                                                  sentence  \
0           A small ring was the only thing found near the old bell.
1           A small ring was the only thing found near the old bell.
2           A small ring was the only thing found near the old bell.
3           A small ring was the only thing found near the old bell.
4           A small ring was the only thing found near the old bell.

query_mode     model prompt_style  shot   api  manual
0             claude          cot   few  True    True
1             claude          cot  zero  True    True
2             claude       direct   few  True    True
3             claude       direct  zero  True    True
4           deepseek          cot   few  True    True

In [109]:
table, pvalue, n, test_type = run_mcnemar(api_manual_wide, 'api', 'manual')
print(table)
print(pvalue, n, test_type)

manual  False  True
api
False       6      6
True       13    119
0.1670684814453125 19 exact

In [110]:
table, pvalue, n, test_type = run_mcnemar(api_manual_wide, 'api', 'manual')
api_man_result_df = pd.DataFrame([{
    "comparison": "API vs Manual",
    "both_correct": table.loc[True, True],
    "api_correct_manual_wrong": table.loc[True, False],
    "api_wrong_manual_correct": table.loc[False, True],
    "both_wrong": table.loc[False, False],
    "discordant_pairs": n,
    "test_type": test_type,
    "p_value": pvalue
}])
api_man_result_df

,comparison,both_correct,api_correct_manual_wrong,api_wrong_manual_correct,both_wrong,discordant_pairs,test_type,p_value
0,API vs Manual,119,13,6,6,19,exact,0.167068

In [111]:
#Primary tests
#CoT vs Direct
cot_direct_wide = pd.pivot_table(
    sub_dedup,
    values='correct',
    index=['sentence', 'model', 'shot','query_mode'],
    columns= 'prompt_style',
    aggfunc='first'
).reset_index()
table, pvalue, n, test_type = run_mcnemar(cot_direct_wide, 'cot', 'direct')
cot_direct_wide_df = pd.DataFrame([{
    "comparison": "CoT vs Direct",
    "both_correct": table.loc[True, True],
    "api_correct_manual_wrong": table.loc[True, False],
    "api_wrong_manual_correct": table.loc[False, True],
    "both_wrong": table.loc[False, False],
    "discordant_pairs": n,
    "test_type": test_type,
    "p_value": pvalue
}])
cot_direct_wide_df

,comparison,both_correct,api_correct_manual_wrong,api_wrong_manual_correct,both_wrong,discordant_pairs,test_type,p_value
0,CoT vs Direct,124,6,3,11,9,exact,0.507812

In [112]:
#CoT Effect Size
effect = (table.loc[True, False] - table.loc[False, True]) / n if n > 0 else 0
effect

0.3333333333333333

In [113]:
#Primary tests
#Zero vs Few
zero_few_wide = pd.pivot_table(
    sub_dedup,
    values='correct',
    index=['sentence', 'model', 'prompt_style','query_mode'],
    columns= 'shot',
    aggfunc='first'
).reset_index()

table, pvalue, n, test_type = run_mcnemar(zero_few_wide, 'zero', 'few')
zero_few_wide_result_df = pd.DataFrame([{
    "comparison": "Zero vs Few",
    "both_correct": table.loc[True, True],
    "api_correct_manual_wrong": table.loc[True, False],
    "api_wrong_manual_correct": table.loc[False, True],
    "both_wrong": table.loc[False, False],
    "discordant_pairs": n,
    "test_type": test_type,
    "p_value": pvalue
}])
zero_few_wide_result_df

,comparison,both_correct,api_correct_manual_wrong,api_wrong_manual_correct,both_wrong,discordant_pairs,test_type,p_value
0,Zero vs Few,120,4,13,7,17,exact,0.049042

In [ ]:
table, pvalue, n, test_type = run_mcnemar(zero_few_wide, 'zero', 'few')
print(table)
print(pvalue, n, test_type)

few    False  True
zero
False      7     13
True       4    120
0.049041748046875 17 exact

:

In [ ]:
#Zero Few Effect Size
effect = (table.loc[True, False] - table.loc[False, True]) / n if n > 0 else 0
effect

-0.5294117647058824

In [ ]:
#Changing McNemar to check for robustness
from statsmodels.stats.contingency_tables import mcnemar

def run_mcnemar(df, colA, colB):

    tmp = df[[colA, colB]].dropna().copy()

    table = pd.crosstab(tmp[colA], tmp[colB])
    table = table.reindex(index=[False, True], columns=[False, True], fill_value=0)

    b = table.loc[True, False]
    c = table.loc[False, True]
    n = b + c
#adding different tests per number discordant pairs
    if n <= 25:
        result = mcnemar(table, exact=False, correction=True)
        test_type = "exact"
    else:
        result = mcnemar(table, exact=False, correction=True)
        test_type = "asymptotic"

    return table, result.pvalue, n, test_type