In [20]:
from pathlib import Path
import pandas as pd

# Get the notebook's directory
notebook_dir = Path.cwd()
file_path = notebook_dir / "ambiguous_responses_raw.csv"

In [21]:
# A smaller subsection of 156 responses were generated for manual and API calls (total 312).
# These sentences were more ambiguous and designed to suggest more than one
# The responses below are API calls
aapi = pd.read_csv(file_path)
aapi.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-20T06:08:05+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","In this sentence, the word ""bank"" refers to the land alongside a river or stream.",bank_river,True
1,run_2,2026-03-20T06:08:10+00:00,gpt-4.1-mini,0,300,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","Step 1: Identify the context of the sentence. \nThe sentence is: ""They sat on the bank after wi...",bank_river,True
2,run_3,2026-03-20T06:08:12+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",Answer: a financial institution,bank_fin,False
3,run_4,2026-03-20T06:08:18+00:00,gpt-4.1-mini,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Let's analyze the sentence step by step:\n\n1. The sentence is: ""They sat on the bank after with...",bank_river,True
4,run_5,2026-03-20T06:08:23+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...","In this sentence, the word ""bank"" refers to the land alongside a river or lake. The mention of ""...",bank_river,True

In [22]:
aapi.shape

(156, 19)

In [23]:
aapi.isna().sum()

response_id           0
timestamp_utc         0
model                 0
temperature           0
max_output_tokens     0
prompt_id             0
run_id                0
target_word           0
sense_id              0
gold_sense            0
sense_family          0
context_type          0
few_shot_policy_id    0
query_mode            0
sentence              0
prompt_text           0
response_text         0
predicted_sense       7
correct               0
dtype: int64

In [24]:
# 7 responses in API call were cut due to length constraint of 300 tokens. 
# These responses will be dropped, with tokens increased to 500 to gather
# full responses.
aapi_drop = aapi.dropna()
aapi_drop.isna().sum()

response_id           0
timestamp_utc         0
model                 0
temperature           0
max_output_tokens     0
prompt_id             0
run_id                0
target_word           0
sense_id              0
gold_sense            0
sense_family          0
context_type          0
few_shot_policy_id    0
query_mode            0
sentence              0
prompt_text           0
response_text         0
predicted_sense       0
correct               0
dtype: int64

In [25]:
aapi_drop.shape

(149, 19)

In [26]:
laapi = pd.read_csv("long_ambiguous_responses_raw.csv")
laapi.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_2,2026-03-22T04:20:13+00:00,gpt-4.1-mini,0,500,cot_zero_v1,1,pitch,pitch_sales,sales_communication,communication,business_communication,same_word_cross_sense,api,"He adjusted his pitch slightly, hoping the crowd would respond better.","Sentence: ""He adjusted his pitch slightly, hoping the crowd would respond better.""\n\nQuestion:\...","Step-by-step reasoning:\n\n1. Identify the context: The sentence mentions ""He adjusted his pitch...",pitch_tone,False
1,run_2,2026-03-22T04:37:29+00:00,deepseek-chat,0,500,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","Let’s break this down step by step. \n\n1. **First, look at the sentence structure and key acti...",bank_river,True
2,run_6,2026-03-22T04:37:53+00:00,deepseek-chat,0,500,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...",Let’s break this down step by step. \n\n1. **Read the sentence**: \n *“The bank was quiet th...,bank_river,True
3,run_10,2026-03-22T04:38:20+00:00,deepseek-chat,0,500,cot_zero_v1,1,pitch,pitch_sales,sales_communication,communication,business_communication,same_word_cross_sense,api,"He adjusted his pitch slightly, hoping the crowd would respond better.","Sentence: ""He adjusted his pitch slightly, hoping the crowd would respond better.""\n\nQuestion:\...",Let’s break this down step by step. \n\n1. **Context clues in the sentence** \n - The subjec...,pitch_sales,True
4,run_12,2026-03-22T04:38:34+00:00,deepseek-chat,0,500,cot_few_v1,1,pitch,pitch_sales,sales_communication,communication,business_communication,same_word_cross_sense,api,"He adjusted his pitch slightly, hoping the crowd would respond better.","Sentence: ""She stepped forward to pitch the stone into the lake.""\nQuestion:\nIn this sentence, ...",Let’s break this down step by step. \n\n1. **Look at the context clues in the sentence:** \n ...,pitch_sales,True

In [27]:
laapi.shape

(7, 19)

In [28]:
# 156 manual responses from
aman = pd.read_excel("manual_ambiguous_responses_raw.xlsm")
aman.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-22 01:13:22,gpt-5.2,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","In this sentence, **“bank”** means **the land along the side of a river** (a riverbank).\n\nEven...",bank_river,True
1,run_2,2026-03-22 01:13:26,gpt-5.2,ui_default,ui_default,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...",“Bank” here means **the side of a river or stream**.\n\nReasoning summary: the sentence includes...,bank_river,True
2,run_3,2026-03-22 01:14:15,gpt-5.2,ui_default,ui_default,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",the land alongside a river,bank_river,True
3,run_4,2026-03-22 01:14:22,gpt-5.2,ui_default,ui_default,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",The sentence is ambiguous because it includes clues for both meanings of **bank**:\n\n* **“withd...,bank_river,True
4,run_5,2026-03-22 01:14:33,gpt-5.2,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,manual,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...","It means the **side of a river or pond**.\n\nThe clue is **“ducks nearby,”** which suggests a na...",bank_river,True

In [29]:
aman.shape

(156, 19)

In [34]:
few_am = pd.read_csv("ambiguous_few_shot_only_responses_raw.csv")
few_am.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-05-25T06:39:22+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",Answer: a financial institution,bank_fin,False
1,run_2,2026-05-25T06:39:24+00:00,gpt-4.1-mini,0,300,direct_few_v1,2,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",Answer: a financial institution,bank_fin,False
2,run_3,2026-05-25T06:39:28+00:00,gpt-4.1-mini,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Step 1: Analyze the context of the sentence: ""They sat on the bank after withdrawing cash, watch...",bank_river,True
3,run_4,2026-05-25T06:39:32+00:00,gpt-4.1-mini,0,300,cot_few_v1,2,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Step 1: Analyze the context of the sentence. \nThe sentence says, ""They sat on the bank after w...",bank_river,True
4,run_5,2026-05-25T06:39:34+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""He deposited money in the bank.""\nQuestion:\nIn this sentence, what does the word ""ba...",Answer: the land alongside a river,bank_river,True

In [35]:
few_am.isna().sum()

response_id           0
timestamp_utc         0
model                 0
temperature           0
max_output_tokens     0
prompt_id             0
run_id                0
target_word           0
sense_id              0
gold_sense            0
sense_family          0
context_type          0
few_shot_policy_id    0
query_mode            0
sentence              0
prompt_text           0
response_text         0
predicted_sense       1
correct               0
dtype: int64

In [36]:
# One response in API call was cut due to length constraint of 300 tokens. 
# This responses will be dropped, with tokens increased to 500 to gather
# full response.
few_am_drop = few_am.dropna()
few_am_drop.isna().sum()

response_id           0
timestamp_utc         0
model                 0
temperature           0
max_output_tokens     0
prompt_id             0
run_id                0
target_word           0
sense_id              0
gold_sense            0
sense_family          0
context_type          0
few_shot_policy_id    0
query_mode            0
sentence              0
prompt_text           0
response_text         0
predicted_sense       0
correct               0
dtype: int64

In [37]:
few_am_drop.shape

(155, 19)

In [38]:
rerun_few=pd.read_csv("rerun_ambiguous_few_shot_only_responses_raw.csv")
rerun_few

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-05-25T08:12:01+00:00,claude-sonnet-4-5-20250929,0,500,cot_few_v1,1,tie,tie_apparel,clothing_accessory,physical_object,social_formal,same_word_cross_sense,api,No one expected the tie to be the most talked-about part of the evening.,"Sentence: ""She bought a silk tie for the formal event.""\nQuestion:\nIn this sentence, what does ...",Let me work through this step by step:\n\n**Step 1: Examine the context**\n- The sentence mentio...,ambiguous,False

In [39]:
pd.set_option('display.max_colwidth', 100)
aapi_man = pd.concat([aapi_drop,aman,laapi,few_am_drop,rerun_few],ignore_index=True)
aapi_man.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-20T06:08:05+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","In this sentence, the word ""bank"" refers to the land alongside a river or stream.",bank_river,True
1,run_2,2026-03-20T06:08:10+00:00,gpt-4.1-mini,0,300,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""They sat on the bank after withdrawing cash, watching the water flow by.""\n\nQuestion...","Step 1: Identify the context of the sentence. \nThe sentence is: ""They sat on the bank after wi...",bank_river,True
2,run_3,2026-03-20T06:08:12+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",Answer: a financial institution,bank_fin,False
3,run_4,2026-03-20T06:08:18+00:00,gpt-4.1-mini,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"They sat on the bank after withdrawing cash, watching the water flow by.","Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Let's analyze the sentence step by step:\n\n1. The sentence is: ""They sat on the bank after with...",bank_river,True
4,run_5,2026-03-20T06:08:23+00:00,gpt-4.1-mini,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,"The bank was quiet that morning, aside from the sound of ducks nearby.","Sentence: ""The bank was quiet that morning, aside from the sound of ducks nearby.""\n\nQuestion:\...","In this sentence, the word ""bank"" refers to the land alongside a river or lake. The mention of ""...",bank_river,True

In [40]:
aapi_man['query_mode'].value_counts()

query_mode
api       312
manual    156
Name: count, dtype: int64

In [41]:
aapi_man.shape

(468, 19)

In [42]:
aapi_man['model'].value_counts()

model
deepseek-chat                 156
gpt-4.1-mini                  104
claude-sonnet-4-20250514       52
gpt-5.2                        52
claude-sonnet-4-5              52
claude-sonnet-4-5-20250929     52
Name: count, dtype: int64

In [43]:
aapi_man['correct'].value_counts()

correct
True     425
False     43
Name: count, dtype: int64

In [45]:
#Creating a subset of only the columns needed
sub = (
    aapi_man[['sentence','query_mode','correct','context_type']]
    .copy()
    .assign(
        prompt_type=aapi_man['prompt_id'].str.split('_').str[0],
        shot_type=aapi_man['prompt_id'].str.split('_').str[1],
        model=aapi_man['model'].str.split('-').str[0]
    )
)
new_order = ['sentence','model','query_mode','prompt_type',
             'shot_type','context_type','correct']
sub = sub[new_order]
sub.head()

,sentence,model,query_mode,prompt_type,shot_type,context_type,correct
0,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,zero,physical_environment,True
1,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,zero,physical_environment,True
2,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,direct,few,physical_environment,False
3,"They sat on the bank after withdrawing cash, watching the water flow by.",gpt,api,cot,few,physical_environment,True
4,"The bank was quiet that morning, aside from the sound of ducks nearby.",gpt,api,direct,zero,physical_environment,True

In [46]:
sub.to_csv("../responses/ambiguous_mixed-effects.csv",index = False)

At this point, work switched to R to use mixed-effects models