In [1]:
import pandas as pd
api = pd.read_csv("responses/responses_raw.csv")
api.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-02T22:30:02+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...","In this sentence, the word **""bank""** means th...",bank_river,True
1,run_2,2026-03-02T22:30:12+00:00,deepseek-chat,0,300,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...",Let’s break this down step by step. \n\n1. **...,bank_river,True
2,run_3,2026-03-02T22:30:14+00:00,deepseek-chat,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river,bank_river,True
3,run_4,2026-03-02T22:30:23+00:00,deepseek-chat,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",Let’s go step by step. \n\n1. The sentence is...,bank_river,True
4,run_5,2026-03-02T22:30:27+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,Extreme flooding has caused the bank to erode ...,"Sentence: ""Extreme flooding has caused the ban...","In this sentence, **""bank""** refers to the **l...",bank_river,True

In [2]:
man = pd.read_csv("responses/responses_manual.csv")
man.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,...,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct,Unnamed: 19,Unnamed: 20
0,manual_1,3/3/2026 21:35,deepseek-chat,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...","In this sentence, ""bank"" means the side of the...",bank_river,True,NaN,NaN
1,manual_2,3/4/2026 21:35,deepseek-chat,ui_default,ui_default,cot_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...",Let’s work through this step by step.\n\n**Ste...,bank_river,True,NaN,NaN
2,manual_3,3/4/2026 21:44,deepseek-chat,ui_default,ui_default,direct_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river,bank_river,True,NaN,NaN
3,manual_4,3/4/2026 21:48,deepseek-chat,ui_default,ui_default,cot_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...","In this sentence, **""bank""** refers to the **s...",bank_river,True,NaN,NaN
4,manual_5,3/4/2026 21:55,deepseek-chat,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,Extreme flooding has caused the bank to erode ...,"Sentence: ""Extreme flooding has caused the ban...","In this sentence, ""bank"" refers to the side of...",bank_river,True,NaN,NaN

In [3]:
pd.set_option('display.max_colwidth', 100)
api_man = pd.concat([api,man],ignore_index=True)
api_man.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,...,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct,Unnamed: 19,Unnamed: 20
0,run_1,2026-03-02T22:30:02+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The fisherman sat quietly on the bank watching the water.""\n\nQuestion:\nIn this sent...","In this sentence, the word **""bank""** means the **land alongside a river or stream**.\n\nThe con...",bank_river,True,NaN,NaN
1,run_2,2026-03-02T22:30:12+00:00,deepseek-chat,0,300,cot_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The fisherman sat quietly on the bank watching the water.""\n\nQuestion:\nExplain your...",Let’s break this down step by step. \n\n1. **Read the sentence:** \n *“The fisherman sat qui...,bank_river,True,NaN,NaN
2,run_3,2026-03-02T22:30:14+00:00,deepseek-chat,0,300,direct_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",the land alongside a river,bank_river,True,NaN,NaN
3,run_4,2026-03-02T22:30:23+00:00,deepseek-chat,0,300,cot_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Let’s go step by step. \n\n1. The sentence is: *""The fisherman sat quietly on the bank watching...",bank_river,True,NaN,NaN
4,run_5,2026-03-02T22:30:27+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,Extreme flooding has caused the bank to erode over time.,"Sentence: ""Extreme flooding has caused the bank to erode over time.""\n\nQuestion:\nIn this sente...","In this sentence, **""bank""** refers to the **land alongside a river or stream** (a riverbank).\n...",bank_river,True,NaN,NaN

In [4]:
api_man['query_mode'].value_counts()

query_mode
api       660
manual    660
Name: count, dtype: int64

In [5]:
api_man.shape

(1320, 21)

In [6]:
api_man['model'].value_counts()

model
deepseek-chat        440
claude-sonnet-4-5    440
gpt-4.1-mini         220
gpt-5.2              220
Name: count, dtype: int64

In [7]:
#Creating a subset of only the columns needed
sub = (
    api_man[['sentence','query_mode','correct']]
    .copy()
    .assign(
        prompt_style=api_man['prompt_id'].str.split('_').str[0],
        shot=api_man['prompt_id'].str.split('_').str[1],
        model=api_man['model'].str.split('-').str[0]
    )
)
new_order = ['sentence','model','query_mode','prompt_style','shot','correct']
sub = sub[new_order]
sub.head()

,sentence,model,query_mode,prompt_style,shot,correct
0,The fisherman sat quietly on the bank watching the water.,deepseek,api,direct,zero,True
1,The fisherman sat quietly on the bank watching the water.,deepseek,api,cot,zero,True
2,The fisherman sat quietly on the bank watching the water.,deepseek,api,direct,few,True
3,The fisherman sat quietly on the bank watching the water.,deepseek,api,cot,few,True
4,Extreme flooding has caused the bank to erode over time.,deepseek,api,direct,zero,True

In [8]:
sub['condition'] = sub['query_mode'].astype(str)+"_"+sub['prompt_style'].astype(str)+"_"+sub['shot'].astype(str)
sub.head()

,sentence,model,query_mode,prompt_style,shot,correct,condition
0,The fisherman sat quietly on the bank watching the water.,deepseek,api,direct,zero,True,api_direct_zero
1,The fisherman sat quietly on the bank watching the water.,deepseek,api,cot,zero,True,api_cot_zero
2,The fisherman sat quietly on the bank watching the water.,deepseek,api,direct,few,True,api_direct_few
3,The fisherman sat quietly on the bank watching the water.,deepseek,api,cot,few,True,api_cot_few
4,Extreme flooding has caused the bank to erode over time.,deepseek,api,direct,zero,True,api_direct_zero

In [9]:
dupes = (
    sub.groupby(['sentence', 'model', 'condition'])
       .size()
       .reset_index(name='n')
       .query('n > 1')
)

dupes.head()

,sentence,model,condition,n
216,"Every Friday, I deposit my paycheck in the bank.",claude,api_cot_few,2
217,"Every Friday, I deposit my paycheck in the bank.",claude,api_cot_zero,2
218,"Every Friday, I deposit my paycheck in the bank.",claude,api_direct_few,2
219,"Every Friday, I deposit my paycheck in the bank.",claude,api_direct_zero,2
220,"Every Friday, I deposit my paycheck in the bank.",claude,manual_cot_few,2

In [10]:
check = (
    sub.groupby(['sentence', 'model', 'condition'])['correct']
       .nunique()
       .reset_index(name='n_unique')
)

check.query('n_unique > 1').head(20)

,sentence,model,condition,n_unique
558,"Janice and Steve took their family to a picnic, enjoying the breeze near the bank.",claude,manual_direct_few,2

In [11]:
sub.query("sentence =='Janice and Steve took their family to a picnic, enjoying the breeze near the bank.' "
"& model == 'claude'& condition =='manual_direct_few'")

,sentence,model,query_mode,prompt_style,shot,correct,condition
890,"Janice and Steve took their family to a picnic, enjoying the breeze near the bank.",claude,manual,direct,few,False,manual_direct_few
918,"Janice and Steve took their family to a picnic, enjoying the breeze near the bank.",claude,manual,direct,few,True,manual_direct_few

In [12]:
sub_dedup = sub.drop_duplicates()

In [13]:
sub_dedup.shape

(1153, 7)

In [14]:
sub_dedup.query("sentence =='Janice and Steve took their family to a picnic, enjoying the breeze near the bank.' "
"& model == 'claude'& condition =='manual_direct_few'")

,sentence,model,query_mode,prompt_style,shot,correct,condition
890,"Janice and Steve took their family to a picnic, enjoying the breeze near the bank.",claude,manual,direct,few,False,manual_direct_few
918,"Janice and Steve took their family to a picnic, enjoying the breeze near the bank.",claude,manual,direct,few,True,manual_direct_few

In [15]:
sub_first = sub_dedup[~((sub_dedup['sentence']=='Janice and Steve took their family to a picnic, enjoying the breeze near the bank.')
                      & (sub_dedup['correct']==True) &
                      (sub_dedup['model']=='claude') &
                      (sub_dedup['condition']=='manual_direct_few'))]
sub_first.shape

(1152, 7)

In [16]:
sub_first.query("sentence =='Janice and Steve took their family to a picnic, enjoying the breeze near the bank.' "
"& model == 'claude'& condition =='manual_direct_few'")

,sentence,model,query_mode,prompt_style,shot,correct,condition
890,"Janice and Steve took their family to a picnic, enjoying the breeze near the bank.",claude,manual,direct,few,False,manual_direct_few

In [26]:
#stratified tests
sub_wide = pd.pivot_table(
    sub_first,
    values='correct',
    index=['sentence','model'],
    columns='condition',
    aggfunc='first'
)
sub_wide.head()

condition                                                       api_cot_few  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude           True
                                                      deepseek         True
                                                      gpt              True
A ring of stones surrounded the fire pit.             claude           True
                                                      deepseek         True

condition                                                       api_cot_zero  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude            True
                                                      deepseek          True
                                                      gpt               True
A ring of stones surrounded the fire pit.             claude            True
                                                      deepseek          True

condition                                                       api_direct_few  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude              True
                                                      deepseek            True
                                                      gpt                 True
A ring of stones surrounded the fire pit.             claude              True
                                                      deepseek            True

condition                                                       api_direct_zero  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude               True
                                                      deepseek             True
                                                      gpt                  True
A ring of stones surrounded the fire pit.             claude               True
                                                      deepseek             True

condition                                                       manual_cot_few  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude              True
                                                      deepseek            True
                                                      gpt                 True
A ring of stones surrounded the fire pit.             claude              True
                                                      deepseek            True

condition                                                       manual_cot_zero  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude               True
                                                      deepseek             True
                                                      gpt                  True
A ring of stones surrounded the fire pit.             claude               True
                                                      deepseek             True

condition                                                       manual_direct_few  \
sentence                                              model
A dark ring appeared around the stain after it dried. claude                 True
                                                      deepseek               True
                                                      gpt                    True
A ring of stones surrounded the fire pit.             claude                 True
                                                      deepseek               True

condition                                                       manual_direct_zero
sentence                                              model
A dark ring appeared around the stain after it dried. claude                  True
                                                      deepseek                True
                                                      gpt                     True
A ring of stones surrounded the fire pit.             claude                  True
                                                      deepseek                True

Comparisons:    
CoT vs Direct  
Few vs Zero  
Manual vs API  
CoT Few vs CoT Zero  
Direct Few vs Direct Zero

In [18]:
sub_wide_df = sub_wide.reset_index()
sub_wide_df.head()

condition,sentence,model,api_cot_few,api_cot_zero,api_direct_few,api_direct_zero,manual_cot_few,manual_cot_zero,manual_direct_few,manual_direct_zero
0,A dark ring appeared around the stain after it dried.,claude,True,True,True,True,True,True,True,True
1,A dark ring appeared around the stain after it dried.,deepseek,True,True,True,True,True,True,True,True
2,A dark ring appeared around the stain after it dried.,gpt,True,True,True,True,True,True,True,True
3,A ring of stones surrounded the fire pit.,claude,True,True,True,True,True,True,True,True
4,A ring of stones surrounded the fire pit.,deepseek,True,True,True,True,True,True,True,True

In [19]:
sub_wide_df.to_csv("sub_sentence.csv", index=False)

In [24]:
#Function to run McNemar Tests
from statsmodels.stats.contingency_tables import mcnemar

def run_mcnemar(df, colA, colB):

    tmp = df[[colA, colB]].dropna().copy()

    table = pd.crosstab(tmp[colA], tmp[colB])
    table = table.reindex(index=[False, True], columns=[False, True], fill_value=0)

    b = table.loc[True, False]
    c = table.loc[False, True]
    n = b + c
#adding different tests per number discordant pairs
    if n <= 25:
        result = mcnemar(table, exact=True)
        test_type = "exact"
    else:
        result = mcnemar(table, exact=False, correction=True)
        test_type = "asymptotic"

    return table, result.pvalue, n, test_type

In [25]:
# Stratified comparison conditions
comparison_specs = {
    "CoT vs Direct": [
        ("api_cot_zero", "api_direct_zero"),
        ("api_cot_few", "api_direct_few"),
        ("manual_cot_zero", "manual_direct_zero"),
        ("manual_cot_few", "manual_direct_few"),
    ],
    "Few vs Zero": [
        ("api_cot_few", "api_cot_zero"),
        ("api_direct_few", "api_direct_zero"),
        ("manual_cot_few", "manual_cot_zero"),
        ("manual_direct_few", "manual_direct_zero"),
    ],
    "Manual vs API": [
        ("manual_cot_zero", "api_cot_zero"),
        ("manual_cot_few", "api_cot_few"),
        ("manual_direct_zero", "api_direct_zero"),
        ("manual_direct_few", "api_direct_few"),
    ],
    "CoT Few vs CoT Zero": [
        ("api_cot_few", "api_cot_zero"),
        ("manual_cot_few", "manual_cot_zero"),
    ],
    "Direct Few vs Direct Zero": [
        ("api_direct_few", "api_direct_zero"),
        ("manual_direct_few", "manual_direct_zero"),
    ],
}

results = []

In [22]:
for model_name in sub_wide_df["model"].dropna().unique():
    df_model = sub_wide_df[sub_wide_df["model"] == model_name].copy()

    for comparison_name, pairs in comparison_specs.items():
        for colA, colB in pairs:
            table, pvalue = run_mcnemar(df_model, colA, colB)

            # Safely extract 2x2 counts even if some combinations are absent
            a = table.loc[True, True] if True in table.index and True in table.columns else 0
            b = table.loc[True, False] if True in table.index and False in table.columns else 0
            c = table.loc[False, True] if False in table.index and True in table.columns else 0
            d = table.loc[False, False] if False in table.index and False in table.columns else 0

            results.append({
                "model": model_name,
                "comparison": comparison_name,
                "condition_A": colA,
                "condition_B": colB,
                "both_correct": a,
                "A_correct_B_wrong": b,
                "A_wrong_B_correct": c,
                "both_wrong": d,
                "p_value": pvalue
            })

results_df = pd.DataFrame(results)
results_df.head()

,model,comparison,condition_A,condition_B,both_correct,A_correct_B_wrong,A_wrong_B_correct,both_wrong,p_value
0,claude,CoT vs Direct,api_cot_zero,api_direct_zero,48,0,0,0,1.0
1,claude,CoT vs Direct,api_cot_few,api_direct_few,48,0,0,0,1.0
2,claude,CoT vs Direct,manual_cot_zero,manual_direct_zero,47,1,0,0,1.0
3,claude,CoT vs Direct,manual_cot_few,manual_direct_few,47,1,0,0,1.0
4,claude,Few vs Zero,api_cot_few,api_cot_zero,48,0,0,0,1.0

In [23]:
results_df.to_csv("mcnemar_results.csv",index=False)

In [28]:
#Primary tests
#API vs Manual
api_manual_wide = pd.pivot_table(
    sub_first,
    values='correct',
    index=['sentence', 'model'],
    columns='query_mode',
    aggfunc='first'
).reset_index()
api_manual_wide.head()

query_mode,sentence,model,api,manual
0,A dark ring appeared around the stain after it dried.,claude,True,True
1,A dark ring appeared around the stain after it dried.,deepseek,True,True
2,A dark ring appeared around the stain after it dried.,gpt,True,True
3,A ring of stones surrounded the fire pit.,claude,True,True
4,A ring of stones surrounded the fire pit.,deepseek,True,True

In [31]:
table, pvalue, n, test_type = run_mcnemar(api_manual_wide, 'api', 'manual')
api_man_result_df = pd.DataFrame([{
    "comparison": "API vs Manual",
    "both_correct": table.loc[True, True],
    "api_correct_manual_wrong": table.loc[True, False],
    "api_wrong_manual_correct": table.loc[False, True],
    "both_wrong": table.loc[False, False],
    "discordant_pairs": n,
    "test_type": test_type,
    "p_value": pvalue
}])
api_man_result_df

,comparison,both_correct,api_correct_manual_wrong,api_wrong_manual_correct,both_wrong,discordant_pairs,test_type,p_value
0,API vs Manual,141,1,1,1,2,exact,1.0

In [33]:
#Primary tests
#CoT vs Direct
cot_direct_wide = pd.pivot_table(
    sub_first,
    values='correct',
    index=['sentence', 'model'],
    columns='prompt_style',
    aggfunc='first'
).reset_index()

table, pvalue, n, test_type = run_mcnemar(cot_direct_wide, 'cot', 'direct')
cot_direct_result_df = pd.DataFrame([{
    "comparison": "CoT vs Direct",
    "both_correct": table.loc[True, True],
    "api_correct_manual_wrong": table.loc[True, False],
    "api_wrong_manual_correct": table.loc[False, True],
    "both_wrong": table.loc[False, False],
    "discordant_pairs": n,
    "test_type": test_type,
    "p_value": pvalue
}])
cot_direct_result_df

,comparison,both_correct,api_correct_manual_wrong,api_wrong_manual_correct,both_wrong,discordant_pairs,test_type,p_value
0,CoT vs Direct,142,2,0,0,2,exact,0.5

In [ ]:
#Primary tests
#Zero vs Few
zero_few_wide = pd.pivot_table(
    sub_first,
    values='correct',
    index=['sentence', 'model'],
    columns='shot',
    aggfunc='first'
).reset_index()

table, pvalue, n, test_type = run_mcnemar(zero_few_wide, 'zero', 'few')
zero_few_wide_result_df = pd.DataFrame([{
    "comparison": "Zero vs Few",
    "both_correct": table.loc[True, True],
    "api_correct_manual_wrong": table.loc[True, False],
    "api_wrong_manual_correct": table.loc[False, True],
    "both_wrong": table.loc[False, False],
    "discordant_pairs": n,
    "test_type": test_type,
    "p_value": pvalue
}])
zero_few_wide_result_df

,comparison,both_correct,api_correct_manual_wrong,api_wrong_manual_correct,both_wrong,discordant_pairs,test_type,p_value
0,Zero vs Few,142,0,2,0,2,exact,0.5

: