In [2]:
import pandas as pd
api = pd.read_csv("../responses/responses_raw.csv")
api.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-03-02T22:30:02+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...","In this sentence, the word **""bank""** means th...",bank_river,True
1,run_2,2026-03-02T22:30:12+00:00,deepseek-chat,0,300,cot_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...",Let’s break this down step by step. \n\n1. **...,bank_river,True
2,run_3,2026-03-02T22:30:14+00:00,deepseek-chat,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river,bank_river,True
3,run_4,2026-03-02T22:30:23+00:00,deepseek-chat,0,300,cot_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",Let’s go step by step. \n\n1. The sentence is...,bank_river,True
4,run_5,2026-03-02T22:30:27+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,Extreme flooding has caused the bank to erode ...,"Sentence: ""Extreme flooding has caused the ban...","In this sentence, **""bank""** refers to the **l...",bank_river,True

In [4]:
man = pd.read_csv("../responses/responses_manual.csv")
man.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,...,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct,Unnamed: 19,Unnamed: 20
0,manual_1,3/3/2026 21:35,deepseek-chat,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...","In this sentence, ""bank"" means the side of the...",bank_river,True,NaN,NaN
1,manual_2,3/4/2026 21:35,deepseek-chat,ui_default,ui_default,cot_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The fisherman sat quietly on the ba...",Let’s work through this step by step.\n\n**Ste...,bank_river,True,NaN,NaN
2,manual_3,3/4/2026 21:44,deepseek-chat,ui_default,ui_default,direct_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river,bank_river,True,NaN,NaN
3,manual_4,3/4/2026 21:48,deepseek-chat,ui_default,ui_default,cot_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...","In this sentence, **""bank""** refers to the **s...",bank_river,True,NaN,NaN
4,manual_5,3/4/2026 21:55,deepseek-chat,ui_default,ui_default,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,manual,Extreme flooding has caused the bank to erode ...,"Sentence: ""Extreme flooding has caused the ban...","In this sentence, ""bank"" refers to the side of...",bank_river,True,NaN,NaN

In [5]:
few_shot = pd.read_csv("../responses/few_shot_only_responses_raw.csv")
few_shot.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,sense_family,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct
0,run_1,2026-05-24T07:05:27+00:00,claude-sonnet-4-5-20250929,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river (or body of water),bank_river,True
1,run_1,2026-05-24T07:59:22+00:00,deepseek-chat,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river,bank_river,True
2,run_1,2026-05-24T22:38:44+00:00,deepseek-chat,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",the land alongside a river,bank_river,True
3,run_1,2026-05-24T23:00:44+00:00,gpt-4.1-mini,0,300,direct_few_v1,1,bank,bank_river,riverbank,geographic,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching...,"Sentence: ""The bank approved his mortgage afte...",Answer: the land alongside a river,bank_river,True
4,run_10,2026-05-24T07:59:39+00:00,deepseek-chat,0,300,cot_few_v1,1,bank,bank_fin,financial institution,institution,financial_sense,same_word_cross_sense,api,The bank teller handed me my change.,"Sentence: ""He deposited money in the bank.""\nQ...",Let’s break it down step by step.\n\n1. The se...,bank_fin,True

In [6]:
pd.set_option('display.max_colwidth', 100)
comb_df = pd.concat([api,man,few_shot],ignore_index=True)
comb_df.head()

,response_id,timestamp_utc,model,temperature,max_output_tokens,prompt_id,run_id,target_word,sense_id,gold_sense,...,context_type,few_shot_policy_id,query_mode,sentence,prompt_text,response_text,predicted_sense,correct,Unnamed: 19,Unnamed: 20
0,run_1,2026-03-02T22:30:02+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The fisherman sat quietly on the bank watching the water.""\n\nQuestion:\nIn this sent...","In this sentence, the word **""bank""** means the **land alongside a river or stream**.\n\nThe con...",bank_river,True,NaN,NaN
1,run_2,2026-03-02T22:30:12+00:00,deepseek-chat,0,300,cot_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The fisherman sat quietly on the bank watching the water.""\n\nQuestion:\nExplain your...",Let’s break this down step by step. \n\n1. **Read the sentence:** \n *“The fisherman sat qui...,bank_river,True,NaN,NaN
2,run_3,2026-03-02T22:30:14+00:00,deepseek-chat,0,300,direct_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...",the land alongside a river,bank_river,True,NaN,NaN
3,run_4,2026-03-02T22:30:23+00:00,deepseek-chat,0,300,cot_few_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,The fisherman sat quietly on the bank watching the water.,"Sentence: ""The bank approved his mortgage after reviewing his credit history.""\nQuestion:\nIn th...","Let’s go step by step. \n\n1. The sentence is: *""The fisherman sat quietly on the bank watching...",bank_river,True,NaN,NaN
4,run_5,2026-03-02T22:30:27+00:00,deepseek-chat,0,300,direct_zero_v1,1,bank,bank_river,riverbank,...,physical_environment,same_word_cross_sense,api,Extreme flooding has caused the bank to erode over time.,"Sentence: ""Extreme flooding has caused the bank to erode over time.""\n\nQuestion:\nIn this sente...","In this sentence, **""bank""** refers to the **land alongside a river or stream** (a riverbank).\n...",bank_river,True,NaN,NaN

In [7]:
comb_df['query_mode'].value_counts()

query_mode
api       1320
manual     660
Name: count, dtype: int64

In [8]:
comb_df.shape

(1980, 21)

In [9]:
comb_df['model'].value_counts()

model
deepseek-chat                 660
claude-sonnet-4-5             440
gpt-4.1-mini                  440
gpt-5.2                       220
claude-sonnet-4-5-20250929    220
Name: count, dtype: int64

In [10]:
#Creating a subset of only the columns needed
sub = (
    comb_df[['sentence','query_mode','correct','context_type']]
    .copy()
    .assign(
        prompt_type=comb_df['prompt_id'].str.split('_').str[0],
        shot_type=comb_df['prompt_id'].str.split('_').str[1],
        model=comb_df['model'].str.split('-').str[0]
    )
)
new_order = ['sentence','model','query_mode','prompt_type',
             'shot_type','context_type','correct']
sub = sub[new_order]
sub.head()

,sentence,model,query_mode,prompt_type,shot_type,context_type,correct
0,The fisherman sat quietly on the bank watching the water.,deepseek,api,direct,zero,physical_environment,True
1,The fisherman sat quietly on the bank watching the water.,deepseek,api,cot,zero,physical_environment,True
2,The fisherman sat quietly on the bank watching the water.,deepseek,api,direct,few,physical_environment,True
3,The fisherman sat quietly on the bank watching the water.,deepseek,api,cot,few,physical_environment,True
4,Extreme flooding has caused the bank to erode over time.,deepseek,api,direct,zero,physical_environment,True

In [70]:
sub.to_csv("../responses/mixed-effects.csv",index = False)

At this point, work switched to R to use mixed-effects models